artillery:
  image:
    name: artilleryio/artillery:latest
    entrypoint: [""]
  script: |
    mkdir reports
    /home/node/artillery/bin/run run --output reports/report.json tests/performance/socket-io.yml
    /home/node/artillery/bin/run report --output reports/report.html reports/report.json
  artifacts:
    paths:
      - reports
